<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Añadir Producto</title>
</head>
<body>

    <h2>Añadir producto</h2>
    <form action="index.php?admin&addingProduct" method="post">
        <input type="text" name="productName" placeholder="Nombre">
        <input type="text" name="productDescription" placeholder="Descripción">
        <input type="number" name="productPrice" placeholder="Precio">
        <input type="number" name="productStock" placeholder="Stock">        
        <input type="submit" name="" value="Añadir">
    </form>  
                  
    
    <!-- boton cancelar -->
    <a href="index.php">
        <button>Inicio</button>
    </a>
</body>
</html>