<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar usuario</title>
</head>
<body>
    
        <?php
            echo '<form action="index.php?admin&saveUser='.$user->getId().'" method="POST">
                <input type="text" name="fullname" value="'.$user->getFullName().'">
                <input type="text" name="username" value="'.$user->getUserName().'">
                <input type="email" name="email" value="'.$user->getEmail().'">
                <input type="submit" name="" value="Actualizar datos">
                </form>';
        ?>        
    
    <!-- boton cancelar -->
</body>
</html>