<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar usuario</title>
</head>
<body>
    
        <?php
            echo '<form action="index.php?admin&saveUser='.$user->id.'" method="POST">
                <input type="text" name="fullname" value="'.$user->fullName.'">
                <input type="text" name="username" value="'.$user->userName.'">
                <input type="email" name="email" value="'.$user->email.'">
                <input type="submit" name="" value="Actualizar datos">
                </form>';
        ?>        
    
    <!-- boton cancelar -->
    <a href="index.php">
        <button>Inicio</button>
    </a>
</body>
</html>