<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>

    <h2>Log in</h2>
    <form action="index.php?login" method="post">
    <!-- <form action="index.php" method="post"> -->
        <input type="text" name="userName" id="" placeholder="Usuario">
        <input type="password" name="password" id="" placeholder="Contraseña">
        <input type="submit" name="loggingIn" value="Entrar">
    </form>      
    <a href="index.php">
        <button>Inicio</button>
    </a>
     
</body>
</html>