<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Panel admin</title>
</head>
<body>
    <h1>Panel de administración</h1>
    <?php
        
        if($_SESSION['user']->role == 0) {
            echo '<a href="index.php?login">Login</a><br>';
            echo '<a href="index.php?register">Registro</a><br>';
        } else {
            echo 'Hola '.$_SESSION['user']->fullName.'<br> 
            <a href="index.php?login&logout">Logout</a>';
        }       

    ?>
    
</body>
</html>