<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
</head>
<body>
    
    <h2>Register</h2>
    <form action="index.php?register" method="post">
        <input type="text" name="fullname" placeholder="Nombre completo">
        <input type="text" name="username" placeholder="Usuario">
        <input type="email" name="email" placeholder="Email">
        <input type="password" name="password" placeholder="Contraseña">
        <input type="password" name="password2" placeholder="Repita la contraseña">
        <input type="submit" name="registeringIn" value="Registro">
    </form>
    <a href="index.php">
        <button>Inicio</button>
    </a>
    
</body>
</html>